### ISSUE TITLE
FPS Issues with gunboats(?)

### ISSUE THREAD

**Issue by Mackaral132** [VenomiXeD/DeadAheadIssues#4]
**Describe the bug**
The menu screen appears while in the middle of the waters in Atoll.

**To Reproduce**
Get on a gunboat in Atoll. Have 2 Attack planes, one dive-bomber, and an enemy gunship target you. Have a bunch of fires on the gunboat and have your fps drop to 0.5. Then attempt to get on the rocket launcher in first person so fps drops to 0.0001. Then have your gunboat sink.

**Expected behavior**
I expect this to be fixed.

**Screenshots**
They are attached.

**Additional context**
I have found a lot of bugs so far. Many I didn't have time to get the actual

https://user-images.githubusercontent.com/96366094/147374635-f02330a1-30a8-452a-a92d-da19759ba04d.mp4

 bug in a screen shot.

**Comment by VenomiXeD** [comment]
Cannot reproduce this issue.
