### ISSUE TITLE
IFV has no tires.

### ISSUE THREAD

**Issue by Mackaral132** [VenomiXeD/DeadAheadIssues#5]
**Describe the bug**
Antares IFV doesn't have tires on one side.

**To Reproduce**
Idk. Ask the player in the IFV.

**Expected behavior**
I expected the IFV to get flinged.

**Screenshots**
Are attached.

**Additional context**
Not a common one. Seen it only 2 or 3 times.
![bannana](https://user-images.githubusercontent.com/96366094/147393127-e24893d8-8fb5-472f-a331-429a62fddc38.png)

**Comment by VenomiXeD** [comment]
Known issue, not sure when this will be patched.

**Comment by VenomiXeD** [comment]
As it looks like, IFVs will be replaced in the next coming updates.
