### ISSUE TITLE
Planes get flinged while take off.

### ISSUE THREAD

**Issue by Mackaral132** [VenomiXeD/DeadAheadIssues#6]
**Describe the bug**
The planes keep getting flinged on take off. This is a common problem and have seen it happen more times I can count.
**To Reproduce**
Its random.

**Expected behavior**
I expected my plane to get flinged into the ocean thus a wasted plane.

**Screenshots**
Are attached.

**Additional context**
The screen shot is old but this problem still exists.
![Bannana 2](https://user-images.githubusercontent.com/96366094/147393157-0afd6bad-6635-4aa3-87d6-50632de3b033.png)

**Comment by VenomiXeD** [comment]
Wait for planes in front of you to take off, otherwise you will ram them and collide with them causing you to flip.
